# Simple definition to run boman-cli tool
# Make sure you have boman.yaml file in your repo

trigger:
- master

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8' # 3.6,3.7,3.9 
- script: |
    sudo python3 -m pip install --upgrade pip # optional
    sudo python3 -m pip install -i https://test.pypi.org/simple/ boman-cli-uat==0.22
    sudo boman-cli-uat -a run -u https://devapi.boman.ai/v2/
  displayName: 'install boman-cli and run scan'
